### PR TITLE
Import op

### PR DESCRIPTION
**Pull request by towerofnix**
The problem I was having when coding the `import` op was that I was
`import`ing from the primary stack implementation on my computer so I
had to change a bunch of `import`s, wait, what?

### CODE REVIEW

**Comment by BookOwl** [comment]
Is there anyway that I can try the code before I merge it?

**Comment by towerofnix** [comment]
Yes! Just open up the `import` branch, and run the `importer.stack` program.

**Comment by BookOwl** [comment]
OK, great!

**Comment by BookOwl** [comment]
Great work! Merged.

**Pull request merged**
