### PR TITLE
Merge @liam4's standard library and python importing.

### PR DESCRIPTION
**Pull request by BookOwl**

### CODE REVIEW

**Comment by towerofnix** [comment]
You can merge it..

..but the lib folder contains a lot of stuff that doesn't work at all. :package:

**Comment by towerofnix** [comment]
KILL using multiple branches

it just confuses things

:P :P

**Comment by BookOwl** [comment]
Did you fix the bugs?

**Comment by towerofnix** [comment]
bugs?

Mostly. :package:

I think the only bugs atm are in my stdlib functions, i.e. not in Stack's underlying code. :package:

**Pull request merged**
